version: '3.9'
services:
  db: 
    image: mysql:5.7.37
    restart: always
    volumes:
      - datadb:/var/lib/mysql
      - ./env/mysqlconfig.cnf:/etc/mysql/conf.d/custom.cnf
    # environment:
      # MYSQL_ROOT_PASSWORD:root
      # - MYSQL_ROOT_PASSWORD=root
      # - MYSQL_DATABASE=test
    env_file:
      - ./env/db.env
    ports:
      - 33066:3306
    # container_name: db
  backend:
    build: ./backend
    # build: 
      # context: ./backend
      # dockerfile: Dockerfile
      # args:
      #   - name=value
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    # stdin_open: true
    # tty: true
    depends_on:
      - db
    # container_name: backend

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./frontend/src:/app/src
      # - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend
    # container_name: frontend


volumes:
  datadb:
  

